# Two-tone (IMD) diagnostic wavetable.
# Each frame contains two pure sines at harmonics A and B of the playback
# pitch. Useful for testing intermodulation distortion in effect plugins:
# any output content that is not at A*f or B*f (or their integer multiples)
# is IMD generated by the device under test.
#
# Modes:
#   Fixed Pair    - every frame contains the same A,B (good for A/B with
#                   the effect on/off)
#   Sweep Upper   - A is fixed, B sweeps from A+1 up to Upper across frames
#   Both Sweep    - both A and B move upward across frames, keeping their
#                   ratio constant
#
# Dependencies: numpy, soundfile.
# Install: python3 -m pip install numpy soundfile
#
# Output format: 32-bit float mono WAV at 48 kHz, 2048 samples per frame.
# Each frame is normalized to peak 0.95 (about -0.45 dBFS) so that the two
# sines together don't clip when summed. With float WAV this is purely a
# headroom choice, not a quantization concern.
#
# Expected command-line:
# python two_tone.py <Mode> <Lower> <Upper> <num_frames> <output_folder>

import os
import sys
import numpy as np
import soundfile as sf
import wt_common

SAMPLES_PER_FRAME = 2048
SAMPLE_RATE_HZ = 48000
PEAK = 0.95

def two_tone_frame(harm_a, harm_b):
    s = np.arange(SAMPLES_PER_FRAME)
    t = s / SAMPLES_PER_FRAME
    v = np.sin(2 * np.pi * harm_a * t) + np.sin(2 * np.pi * harm_b * t)
    peak = np.max(np.abs(v))
    return PEAK * v / peak if peak > 0 else v

mode = sys.argv[1]
lower = int(sys.argv[2])
upper = int(sys.argv[3])
num_frames = int(sys.argv[4])
output_path = sys.argv[5]
full_path = os.path.join(output_path, 'wavetable.wav')

frames = []
for i in range(num_frames):
    t = i / max(1, num_frames - 1)
    if mode == 'Fixed Pair':
        a, b = lower, upper
    elif mode == 'Sweep Upper':
        a = lower
        b = max(lower + 1, int(round(lower + 1 + t * max(0, upper - lower - 1))))
    else:  # Both Sweep
        ratio = upper / float(lower) if lower > 0 else 1.0
        a = max(1, int(round(lower * (1.0 + t * 3.0))))
        b = max(a + 1, int(round(a * ratio)))
    frames.append(two_tone_frame(a, b))

data = np.concatenate(frames).astype(np.float32)
sf.write(full_path, data, SAMPLE_RATE_HZ, subtype='FLOAT')

wt_common.write_sidecar(
    output_path, "two_tone.py", "IMD",
    {"Mode": mode, "Lower": lower, "Upper": upper, "#Frames": num_frames},
    sample_rate=SAMPLE_RATE_HZ, samples_per_frame=SAMPLES_PER_FRAME,
    frame_count=num_frames)
